(defun my-color-theme ()
  (interactive)
  (color-theme-install
   '(my-color-theme
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#474747"))))
     (region ((t (:background "#a39f1f"))))
     (font-lock-builtin-face ((t (:foreground "#8cbbed"))))
     (font-lock-comment-face ((t (:foreground "#e60036"))))
     (font-lock-function-name-face ((t (:foreground "#5598fc"))))
     (font-lock-keyword-face ((t (:foreground "#2f8ef4"))))
     (font-lock-string-face ((t (:foreground "#ad7fa8"))))
     (font-lock-type-face ((t (:foreground"#179603"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#bdbdbd" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'my-color-theme)

(when (require 'color-theme nil t)
  (when (not (eq (symbol-value 'window-system) nil))
    (color-theme-initialize)
    (my-color-theme)
    )
  )

